[[redirects]]
  from = "/login"
  to = "/public/login.html"
  status = 200
  force = true

[[redirects]]
  from = "/dashboard"
  to = "/public/dashboard.html"
  status = 200
  force = true

[[redirects]]
  from = "/form-complete"
  to = "/public/form-complete.html"
  status = 200
  force = true

[[redirects]]
  from = "/api/*"
  to = "/api/index.js"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200